const mapTicket = (ticket, technicianname) => ({
    ticket: {
        incidentid:                   ticket.incidentid,
        casetitle:                    ticket.title,
        description:                  ticket.description ?? null,
        statusid:                     ticket.statecode                  ?? null,
        status:                       ticket["statecode@OData.Community.Display.V1.FormattedValue"]   ?? null,
        statusreasonid:               ticket.statuscode ?? null,
        statusreason:                 ticket["statuscode@OData.Community.Display.V1.FormattedValue"]  ?? null,
        isescalated:                  ticket.isescalated,
        ss_ticketstage:               ticket["ss_ticketstage@OData.Community.Display.V1.FormattedValue"] ?? null, 
        _primarycontactid_value:      ticket._primarycontactid_value,
        _ss_assignedtechnician_value: ticket._ss_assignedtechnician_value,
        dynamicsaccountid:                   ticket.customerid_account?.accountid ?? null,
        customername:                 ticket["_customerid_value@OData.Community.Display.V1.FormattedValue"] ?? ticket.customerid_account?.name ?? null,
        contact:                      ticket.primarycontactid?.fullname 
                                    ?? ticket.ss_Contact?.fullname 
                                    ?? null,
        companycontactid:                     ticket.primarycontactid?.contactid 
                                    ?? ticket.ss_Contact?.contactid 
                                    ?? null,
        companycontactemail:                  ticket.ss_Contact?.emailaddress1 
                                    ?? null,  
        ownerid:                      ticket._ownerid_value ?? null,
        ownername:                    ticket["_ownerid_value@OData.Community.Display.V1.FormattedValue"] ?? null,
        originid:                    ticket.caseorigincode ?? null,
        origin:                      ticket["caseorigincode@OData.Community.Display.V1.FormattedValue"] ?? null,
        createdon:                    ticket.createdon,
        modifiedon:                   ticket.modifiedon,
        
    },
    ticketdynamics: {
        ticketnumber:             ticket.ticketnumber,
        autotaskticketnumber:     ticket.ss_autotaskticketnumber    ?? null,
        technicianname,
        technicianid:             ticket._ss_assignedtechnician_value ?? null,
        assignedresource:         ticket["_ss_assignedresource_value@OData.Community.Display.V1.FormattedValue"] ?? null,
        assignedresourceid:       ticket._ss_assignedresource_value  ?? null,
        timezone:                 ticket.ss_timezone                 ?? null,
        schedulestartdate:        ticket.ss_schedulestartdate        ?? null,
        scheduleenddate:          ticket.ss_scheduleenddate          ?? null,
        scheduletype:             ticket.ss_scheduletype             ?? null,
        issuetype:                ticket["_ss_autotaskissuetype_value@OData.Community.Display.V1.FormattedValue"]    ?? null,
        issuetypeid:              ticket._ss_autotaskissuetype_value    ?? null,
        subissuetype:             ticket["_ss_autotasksubissuetype_value@OData.Community.Display.V1.FormattedValue"] ?? null,
        subissuetypeid:           ticket._ss_autotasksubissuetype_value ?? null,
        skillrequired:            ticket.ss_skillrequired            ?? null,
        worktype:                 ticket["ss_worktype@OData.Community.Display.V1.FormattedValue"] ?? null,
        worktypeid:               ticket.ss_worktype                 ?? null,
        duedate:                  ticket.ss_duedate                  ?? null,
        urgency:                  ticket["ss_ticketurgency@OData.Community.Display.V1.FormattedValue"] ?? ticket.ss_ticketurgency ?? null,
        impact:                   ticket.ss_ticketimpact             ?? null,
        source:                   ticket["ss_source@OData.Community.Display.V1.FormattedValue"] ?? null,
        sourceid:                 ticket.ss_source                   ?? null,
        estimatedhours:           ticket.ss_estimatedhours           ?? null,
        actualhours:              ticket.ss_actualhours              ?? null,
        contract:                 ticket["_ss_contract_value@OData.Community.Display.V1.FormattedValue"] ?? null,
        contractid:               ticket._ss_contract_value          ?? null,
        ticketcategory:           ticket["ss_ticketcategory@OData.Community.Display.V1.FormattedValue"] ?? null,
        ticketcategoryid:         ticket.ss_ticketcategory           ?? null,
        tickettype:               ticket["ss_tickettype@OData.Community.Display.V1.FormattedValue"] ?? null,
        tickettypeid:             ticket.ss_tickettype               ?? null,
        priority:                 ticket["prioritycode@OData.Community.Display.V1.FormattedValue"] ?? null,
        priorityid:               ticket.prioritycode                ?? null,
        quickfixflag:             ticket.ss_quickfixflag             ?? null,
        requesttype:              ticket.ss_requesttype              ?? null,
        resolution:               ticket.ss_resolution               ?? null,
        resolveddate:             ticket.ss_resolveddate             ?? null,
        customerconfirmation:     ticket.ss_customerconfirmation     ?? null,
        autotaskid:               ticket.ss_autotaskid               ?? null,
        autotaskurl:              ticket.ss_autotaskurl              ?? null,
        firstresponsedatetime:    ticket.ss_firstresponsedatetime    ?? null,
        firstresponseduedatetime: ticket.ss_firstresponseduedatetime ?? null,
        sla:                      ticket["_slaid_value@OData.Community.Display.V1.FormattedValue"] ?? null,
        slaid:                    ticket._slaid_value                ?? null,
        queue:                    ticket["_ss_queue_value@OData.Community.Display.V1.FormattedValue"] ?? null,
        queueid:                  ticket._ss_queue_value             ?? null,
        project:                  ticket._ss_project_value           ?? null,
        additionalcontacts:       ticket._ss_additionalcontacts_value ?? null,
        creatorresourceid:        ticket.ss_creatorresourceid        ?? null,
        closurenote:              ticket.ss_reason                   ?? null,
        closuredate:              ticket.ss_completedonautotask      ?? null,
        ticketlifecycle:          ticket.ss_ticketstage              ?? null,
        servicelevelagreement:    ticket["_slainvokedid_value@OData.Community.Display.V1.FormattedValue"] ?? null,
    },

    
});

module.exports = { mapTicket };