const INCIDENT_SELECT_FIELDS = [
    "incidentid",
    "title",
    "description",
    "statecode",
    "statuscode",
    "caseorigincode",
    "createdon",
    "modifiedon",
    "isescalated",
    "ss_ticketstage",
    "ticketnumber",
    "prioritycode",
    "_customerid_value",
    "_primarycontactid_value",
    "_ownerid_value",
    "_ss_assignedtechnician_value",
    "_ss_assignedresource_value",
    "_ss_autotaskissuetype_value",
    "_ss_autotasksubissuetype_value",
    "_ss_contract_value",
    "_ss_queue_value",
    "_ss_project_value",
    "_ss_additionalcontacts_value",
    "_slaid_value",
    "_slainvokedid_value",
    "ss_autotaskticketnumber",
    "ss_timezone",
    "ss_schedulestartdate",
    "ss_scheduleenddate",
    "ss_scheduletype",
    "ss_skillrequired",
    "ss_worktype",
    "ss_duedate",
    "ss_ticketurgency",
    "ss_ticketimpact",
    "ss_source",
    "ss_estimatedhours",
    "ss_actualhours",
    "ss_ticketcategory",
    "ss_tickettype",
    "ss_autotaskticketstatus",
    "ss_quickfixflag",
    "ss_requesttype",
    "ss_resolution",
    "ss_resolveddate",
    "ss_customerconfirmation",
    "ss_autotaskid",
    "ss_autotaskurl",
    "ss_firstresponsedatetime",
    "ss_firstresponseduedatetime",
    "ss_creatorresourceid",
    "ss_reason",
    "ss_airouted",
    "ss_completedonautotask",
].join(",");

const INCIDENT_EXPAND_FIELDS = [
     "customerid_account($select=name,accountid,ss_azuretenantid)",
    "primarycontactid($select=fullname,contactid)",
    // "ss_Contact($select=fullname,contactid,emailaddress1)",
     "ss_Contact($select=fullname,contactid,emailaddress1,firstname,lastname,jobtitle,telephone1,mobilephone,department;$expand=parentcustomerid_account($select=accountid,name,ss_azuretenantid))",

].join(",");

module.exports = {
    INCIDENT_SELECT_FIELDS,
    INCIDENT_EXPAND_FIELDS
};